# Generated by Django 3.2.7 on 2021-09-05 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='restaurant',
            new_name='movie',
        ),
    ]
