# Generated by Django 3.2.7 on 2021-09-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0003_rename_restaurant_review_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='password',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
